language: node_js
node_js:
  - "5.3"
before_script: 
  - chmod 0777 ./node_modules/.bin/mocha
  - psql -c 'create database test;' -U postgres
  # - npm run migrate
addons:
  - postgresql: "9.3"
services:
  - postgresql